default_context:
  project_name: 'fastapiproject'
  project_slug: 'fastapiproject'
  domain_main: 'fastapiproject.com'
  domain_staging: 'stag.fastapiproject.com'
  docker_swarm_stack_name_main: 'fastapiproject-com'
  docker_swarm_stack_name_staging: 'stag-fastapiproject-com'
  secret_key: '85c5b70db2c2ff800164462db4d65f6cd76ba64b8c07d42ec6f065e80e8df02f'
  first_superuser: 'admin@fastapiproject.com'
  first_superuser_password: 'superuser'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapiproject.com", "https://stag.fastapiproject.com", "https://fastapiproject.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapiproject.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'postgres'
  traefik_constraint_tag: 'fastapiproject.com'
  traefik_constraint_tag_staging: 'stag.fastapiproject.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:superuser'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
